#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* GraphHopper Directions API
* You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGBreak
@end

@interface SWGBreak : SWGObject

/* earliest start of break [optional]
 */
@property(nonatomic) NSNumber* earliest;
/* latest start of break [optional]
 */
@property(nonatomic) NSNumber* latest;
/* duration of break [optional]
 */
@property(nonatomic) NSNumber* duration;
/* max driving time without break [optional]
 */
@property(nonatomic) NSNumber* maxDrivingTime;
/* initial driving time, i.e. the time your driver has already spent for driving [optional]
 */
@property(nonatomic) NSNumber* initialDrivingTime;
/* array of splits [optional]
 */
@property(nonatomic) NSArray<NSNumber*>* possibleSplit;

@end
