#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* GraphHopper Directions API
* With the GraphHopper Directions API you get reliable and fast web services for routing and more with world wide coverage. We offer A-to-B routing via the Routing API optionally with turn instructions and elevation data as well as route optimization with various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API. 
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGSolution.h"


@protocol SWGResponse
@end

@interface SWGResponse : SWGObject


@property(nonatomic) NSArray<NSString*>* varCopyrights;
/* unique identify of job - which you get when posting your request to the large problem solver [optional]
 */
@property(nonatomic) NSString* jobId;
/* indicates the current status of the job [optional]
 */
@property(nonatomic) NSString* status;
/* waiting time in ms [optional]
 */
@property(nonatomic) NSNumber* waitingInQueue;
/* processing time in ms. if job is still waiting in queue, processing_time is 0 [optional]
 */
@property(nonatomic) NSNumber* processingTime;
/* the solution. only available if status field indicates finished [optional]
 */
@property(nonatomic) SWGSolution* solution;

@end
