#import <Foundation/Foundation.h>
#import "OAIResponse.h"
#import "OAIApi.h"

/**
* GraphHopper Directions API
* You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAISolutionApi: NSObject <OAIApi>

extern NSString* kOAISolutionApiErrorDomain;
extern NSInteger kOAISolutionApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Return the solution associated to the jobId
/// This endpoint returns the solution of a large problems. You can fetch it with the job_id, you have been sent. 
///
/// @param key your API key
/// @param jobId Request solution with jobId
/// 
///  code:200 message:"A response containing the solution",
///  code:400 message:"Error occurred on client side such as invalid input.",
///  code:500 message:"Error occurred on server side."
///
/// @return OAIResponse*
-(NSURLSessionTask*) getSolutionWithKey: (NSString*) key
    jobId: (NSString*) jobId
    completionHandler: (void (^)(OAIResponse* output, NSError* error)) handler;



@end
