# GraphHopper Directions API
# 
# You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
# 
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' RouteResponsePath Class
#'
#' @field distance 
#' @field time 
#' @field ascend 
#' @field descend 
#' @field points 
#' @field points_encoded 
#' @field bbox 
#' @field snapped_waypoints 
#' @field instructions 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RouteResponsePath <- R6::R6Class(
  'RouteResponsePath',
  public = list(
    `distance` = NULL,
    `time` = NULL,
    `ascend` = NULL,
    `descend` = NULL,
    `points` = NULL,
    `points_encoded` = NULL,
    `bbox` = NULL,
    `snapped_waypoints` = NULL,
    `instructions` = NULL,
    initialize = function(`distance`, `time`, `ascend`, `descend`, `points`, `points_encoded`, `bbox`, `snapped_waypoints`, `instructions`){
      if (!missing(`distance`)) {
        stopifnot(is.numeric(`distance`), length(`distance`) == 1)
        self$`distance` <- `distance`
      }
      if (!missing(`time`)) {
        stopifnot(is.numeric(`time`), length(`time`) == 1)
        self$`time` <- `time`
      }
      if (!missing(`ascend`)) {
        stopifnot(is.numeric(`ascend`), length(`ascend`) == 1)
        self$`ascend` <- `ascend`
      }
      if (!missing(`descend`)) {
        stopifnot(is.numeric(`descend`), length(`descend`) == 1)
        self$`descend` <- `descend`
      }
      if (!missing(`points`)) {
        stopifnot(R6::is.R6(`points`))
        self$`points` <- `points`
      }
      if (!missing(`points_encoded`)) {
        self$`points_encoded` <- `points_encoded`
      }
      if (!missing(`bbox`)) {
        stopifnot(is.list(`bbox`), length(`bbox`) != 0)
        lapply(`bbox`, function(x) stopifnot(is.character(x)))
        self$`bbox` <- `bbox`
      }
      if (!missing(`snapped_waypoints`)) {
        stopifnot(R6::is.R6(`snapped_waypoints`))
        self$`snapped_waypoints` <- `snapped_waypoints`
      }
      if (!missing(`instructions`)) {
        stopifnot(R6::is.R6(`instructions`))
        self$`instructions` <- `instructions`
      }
    },
    toJSON = function() {
      RouteResponsePathObject <- list()
      if (!is.null(self$`distance`)) {
        RouteResponsePathObject[['distance']] <- self$`distance`
      }
      if (!is.null(self$`time`)) {
        RouteResponsePathObject[['time']] <- self$`time`
      }
      if (!is.null(self$`ascend`)) {
        RouteResponsePathObject[['ascend']] <- self$`ascend`
      }
      if (!is.null(self$`descend`)) {
        RouteResponsePathObject[['descend']] <- self$`descend`
      }
      if (!is.null(self$`points`)) {
        RouteResponsePathObject[['points']] <- self$`points`$toJSON()
      }
      if (!is.null(self$`points_encoded`)) {
        RouteResponsePathObject[['points_encoded']] <- self$`points_encoded`
      }
      if (!is.null(self$`bbox`)) {
        RouteResponsePathObject[['bbox']] <- self$`bbox`
      }
      if (!is.null(self$`snapped_waypoints`)) {
        RouteResponsePathObject[['snapped_waypoints']] <- self$`snapped_waypoints`$toJSON()
      }
      if (!is.null(self$`instructions`)) {
        RouteResponsePathObject[['instructions']] <- self$`instructions`$toJSON()
      }

      RouteResponsePathObject
    },
    fromJSON = function(RouteResponsePathJson) {
      RouteResponsePathObject <- jsonlite::fromJSON(RouteResponsePathJson)
      if (!is.null(RouteResponsePathObject$`distance`)) {
        self$`distance` <- RouteResponsePathObject$`distance`
      }
      if (!is.null(RouteResponsePathObject$`time`)) {
        self$`time` <- RouteResponsePathObject$`time`
      }
      if (!is.null(RouteResponsePathObject$`ascend`)) {
        self$`ascend` <- RouteResponsePathObject$`ascend`
      }
      if (!is.null(RouteResponsePathObject$`descend`)) {
        self$`descend` <- RouteResponsePathObject$`descend`
      }
      if (!is.null(RouteResponsePathObject$`points`)) {
        pointsObject <- ResponseCoordinates$new()
        pointsObject$fromJSON(jsonlite::toJSON(RouteResponsePathObject$points, auto_unbox = TRUE))
        self$`points` <- pointsObject
      }
      if (!is.null(RouteResponsePathObject$`points_encoded`)) {
        self$`points_encoded` <- RouteResponsePathObject$`points_encoded`
      }
      if (!is.null(RouteResponsePathObject$`bbox`)) {
        self$`bbox` <- RouteResponsePathObject$`bbox`
      }
      if (!is.null(RouteResponsePathObject$`snapped_waypoints`)) {
        snapped_waypointsObject <- ResponseCoordinates$new()
        snapped_waypointsObject$fromJSON(jsonlite::toJSON(RouteResponsePathObject$snapped_waypoints, auto_unbox = TRUE))
        self$`snapped_waypoints` <- snapped_waypointsObject
      }
      if (!is.null(RouteResponsePathObject$`instructions`)) {
        instructionsObject <- ResponseInstructions$new()
        instructionsObject$fromJSON(jsonlite::toJSON(RouteResponsePathObject$instructions, auto_unbox = TRUE))
        self$`instructions` <- instructionsObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "distance": %d,
           "time": %d,
           "ascend": %d,
           "descend": %d,
           "points": %s,
           "points_encoded": %s,
           "bbox": [%s],
           "snapped_waypoints": %s,
           "instructions": %s
        }',
        self$`distance`,
        self$`time`,
        self$`ascend`,
        self$`descend`,
        self$`points`$toJSON(),
        self$`points_encoded`,
        lapply(self$`bbox`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`snapped_waypoints`$toJSON(),
        self$`instructions`$toJSON()
      )
    },
    fromJSONString = function(RouteResponsePathJson) {
      RouteResponsePathObject <- jsonlite::fromJSON(RouteResponsePathJson)
      self$`distance` <- RouteResponsePathObject$`distance`
      self$`time` <- RouteResponsePathObject$`time`
      self$`ascend` <- RouteResponsePathObject$`ascend`
      self$`descend` <- RouteResponsePathObject$`descend`
      ResponseCoordinatesObject <- ResponseCoordinates$new()
      self$`points` <- ResponseCoordinatesObject$fromJSON(jsonlite::toJSON(RouteResponsePathObject$points, auto_unbox = TRUE))
      self$`points_encoded` <- RouteResponsePathObject$`points_encoded`
      self$`bbox` <- RouteResponsePathObject$`bbox`
      ResponseCoordinatesObject <- ResponseCoordinates$new()
      self$`snapped_waypoints` <- ResponseCoordinatesObject$fromJSON(jsonlite::toJSON(RouteResponsePathObject$snapped_waypoints, auto_unbox = TRUE))
      ResponseInstructionsObject <- ResponseInstructions$new()
      self$`instructions` <- ResponseInstructionsObject$fromJSON(jsonlite::toJSON(RouteResponsePathObject$instructions, auto_unbox = TRUE))
    }
  )
)
