//
// Break.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Break: Codable {

    /** earliest start of break */
    public var earliest: Int64?
    /** latest start of break */
    public var latest: Int64?
    /** duration of break */
    public var duration: Int64?
    /** max driving time without break */
    public var maxDrivingTime: Int64?
    /** initial driving time, i.e. the time your driver has already spent for driving */
    public var initialDrivingTime: Int64?
    /** array of splits */
    public var possibleSplit: [Int64]?

    public init(earliest: Int64?, latest: Int64?, duration: Int64?, maxDrivingTime: Int64?, initialDrivingTime: Int64?, possibleSplit: [Int64]?) {
        self.earliest = earliest
        self.latest = latest
        self.duration = duration
        self.maxDrivingTime = maxDrivingTime
        self.initialDrivingTime = initialDrivingTime
        self.possibleSplit = possibleSplit
    }

    public enum CodingKeys: String, CodingKey { 
        case earliest
        case latest
        case duration
        case maxDrivingTime = "max_driving_time"
        case initialDrivingTime = "initial_driving_time"
        case possibleSplit = "possible_split"
    }


}

