//
// CostMatrix.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct CostMatrix: Codable {

    public enum ModelType: String, Codable {
        case _default = "default"
        case google = "google"
    }
    /** type of cost matrix, currently default or google are supported */
    public var type: ModelType?
    /** URL of matrix service */
    public var url: String?
    public var locationIds: [String]?
    /** JSON data of matrix response */
    public var data: Any?
    /** vehicle profile or empty if catch all fallback */
    public var profile: String?

    public init(type: ModelType?, url: String?, locationIds: [String]?, data: Any?, profile: String?) {
        self.type = type
        self.url = url
        self.locationIds = locationIds
        self.data = data
        self.profile = profile
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case url
        case locationIds = "location_ids"
        case data
        case profile
    }


}

