//
// Detail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Detail: Codable {

    /** id of unassigned service/shipment */
    public var _id: String?
    /** reason code */
    public var code: Int?
    /** human readable reason */
    public var reason: String?

    public init(_id: String?, code: Int?, reason: String?) {
        self._id = _id
        self.code = code
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case code
        case reason
    }


}

