//
// Location.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Location: Codable {

    /** longitude */
    public var lon: Double?
    /** latitude */
    public var lat: Double?

    public init(lon: Double?, lat: Double?) {
        self.lon = lon
        self.lat = lat
    }


}

