//
// ResponseCoordinates.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ResponseCoordinates: Codable {

    public var coordinates: ResponseCoordinatesArray?

    public init(coordinates: ResponseCoordinatesArray?) {
        self.coordinates = coordinates
    }


}

