=begin comment

GraphHopper Directions API

With the GraphHopper Directions API you get reliable and fast web services for routing and more with world wide coverage. We offer A-to-B routing via the Routing API optionally with turn instructions and elevation data as well as route optimization with various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API. 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::SwaggerClient::GeocodingApi');

my $api = WWW::SwaggerClient::GeocodingApi->new();
isa_ok($api, 'WWW::SwaggerClient::GeocodingApi');

#
# geocode_get test
#
{
    my $key = undef; # replace NULL with a proper value
    my $q = undef; # replace NULL with a proper value
    my $locale = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $reverse = undef; # replace NULL with a proper value
    my $point = undef; # replace NULL with a proper value
    my $provider = undef; # replace NULL with a proper value
    my $result = $api->geocode_get(key => $key, q => $q, locale => $locale, limit => $limit, reverse => $reverse, point => $point, provider => $provider);
}


1;
