=begin comment

GraphHopper Directions API

You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::SwaggerClient::Object::GHResponseInstruction;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

GraphHopper Directions API

You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::SwaggerClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'GHResponseInstruction',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'text' => {
    	datatype => 'string',
    	base_name => 'text',
    	description => 'A description what the user has to do in order to follow the route. The language depends on the locale parameter.',
    	format => '',
    	read_only => '',
    		},
    'street_name' => {
    	datatype => 'string',
    	base_name => 'street_name',
    	description => 'The name of the street to turn onto in order to follow the route.',
    	format => '',
    	read_only => '',
    		},
    'distance' => {
    	datatype => 'double',
    	base_name => 'distance',
    	description => 'The distance for this instruction, in meter',
    	format => '',
    	read_only => '',
    		},
    'time' => {
    	datatype => 'int',
    	base_name => 'time',
    	description => 'The duration for this instruction, in ms',
    	format => '',
    	read_only => '',
    		},
    'interval' => {
    	datatype => 'ARRAY[int]',
    	base_name => 'interval',
    	description => 'An array containing the first and the last index (relative to paths[0].points) of the points for this instruction. This is useful to know for which part of the route the instructions are valid.',
    	format => '',
    	read_only => '',
    		},
    'sign' => {
    	datatype => 'int',
    	base_name => 'sign',
    	description => 'A number which specifies the sign to show e.g. for right turn etc &lt;br&gt;TURN_SHARP_LEFT &#x3D; -3&lt;br&gt;TURN_LEFT &#x3D; -2&lt;br&gt;TURN_SLIGHT_LEFT &#x3D; -1&lt;br&gt;CONTINUE_ON_STREET &#x3D; 0&lt;br&gt;TURN_SLIGHT_RIGHT &#x3D; 1&lt;br&gt;TURN_RIGHT &#x3D; 2&lt;br&gt;TURN_SHARP_RIGHT &#x3D; 3&lt;br&gt;FINISH &#x3D; 4&lt;br&gt;VIA_REACHED &#x3D; 5&lt;br&gt;USE_ROUNDABOUT &#x3D; 6',
    	format => '',
    	read_only => '',
    		},
    'annotation_text' => {
    	datatype => 'string',
    	base_name => 'annotation_text',
    	description => 'optional - A text describing the instruction in more detail, e.g. like surface of the way, warnings or involved costs.',
    	format => '',
    	read_only => '',
    		},
    'annotation_importance' => {
    	datatype => 'int',
    	base_name => 'annotation_importance',
    	description => 'optional - 0 stands for INFO, 1 for warning, 2 for costs, 3 for costs and warning',
    	format => '',
    	read_only => '',
    		},
    'exit_number' => {
    	datatype => 'int',
    	base_name => 'exit_number',
    	description => 'optional - Only available for USE_ROUNDABOUT instructions. The count of exits at which the route leaves the roundabout.',
    	format => '',
    	read_only => '',
    		},
    'turn_angle' => {
    	datatype => 'double',
    	base_name => 'turn_angle',
    	description => 'optional - Only available for USE_ROUNDABOUT instructions. The radian of the route within the roundabout - 0&amp;lt;r&amp;lt;2*PI for clockwise and -2PI&amp;lt;r&amp;lt;0 for counterclockwise transit. Null if the direction of rotation is undefined.',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'text' => 'string',
    'street_name' => 'string',
    'distance' => 'double',
    'time' => 'int',
    'interval' => 'ARRAY[int]',
    'sign' => 'int',
    'annotation_text' => 'string',
    'annotation_importance' => 'int',
    'exit_number' => 'int',
    'turn_angle' => 'double'
} );

__PACKAGE__->attribute_map( {
    'text' => 'text',
    'street_name' => 'street_name',
    'distance' => 'distance',
    'time' => 'time',
    'interval' => 'interval',
    'sign' => 'sign',
    'annotation_text' => 'annotation_text',
    'annotation_importance' => 'annotation_importance',
    'exit_number' => 'exit_number',
    'turn_angle' => 'turn_angle'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
