/*
 * GraphHopper Directions API
 * With the GraphHopper Directions API you get reliable and fast web services for routing and more with world wide coverage. We offer A-to-B routing via the Routing API optionally with turn instructions and elevation data as well as route optimization with various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.graphhopper.directions.api.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.graphhopper.directions.api.client.model.GHIsochroneResponsePolygonGeometry;
import com.graphhopper.directions.api.client.model.GHIsochroneResponsePolygonProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A found path
 */
@ApiModel(description = "A found path")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T12:21:02.048+11:00")
public class GHIsochroneResponsePolygon {
  @SerializedName("properties")
  private GHIsochroneResponsePolygonProperties properties = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("geometry")
  private GHIsochroneResponsePolygonGeometry geometry = null;

  public GHIsochroneResponsePolygon properties(GHIsochroneResponsePolygonProperties properties) {
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @ApiModelProperty(example = "null", value = "")
  public GHIsochroneResponsePolygonProperties getProperties() {
    return properties;
  }

  public void setProperties(GHIsochroneResponsePolygonProperties properties) {
    this.properties = properties;
  }

  public GHIsochroneResponsePolygon type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public GHIsochroneResponsePolygon geometry(GHIsochroneResponsePolygonGeometry geometry) {
    this.geometry = geometry;
    return this;
  }

   /**
   * Get geometry
   * @return geometry
  **/
  @ApiModelProperty(example = "null", value = "")
  public GHIsochroneResponsePolygonGeometry getGeometry() {
    return geometry;
  }

  public void setGeometry(GHIsochroneResponsePolygonGeometry geometry) {
    this.geometry = geometry;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GHIsochroneResponsePolygon ghIsochroneResponsePolygon = (GHIsochroneResponsePolygon) o;
    return Objects.equals(this.properties, ghIsochroneResponsePolygon.properties) &&
        Objects.equals(this.type, ghIsochroneResponsePolygon.type) &&
        Objects.equals(this.geometry, ghIsochroneResponsePolygon.geometry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(properties, type, geometry);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GHIsochroneResponsePolygon {\n");
    
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    geometry: ").append(toIndentedString(geometry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

