/*
 * GraphHopper Directions API
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.graphhopper.directions.api.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.graphhopper.directions.api.client.model.ResponseCoordinates;
import com.graphhopper.directions.api.client.model.ResponseInstructions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * A found path
 */
@ApiModel(description = "A found path")

public class RouteResponsePath {
  @SerializedName("distance")
  private Double distance = null;

  @SerializedName("time")
  private Long time = null;

  @SerializedName("ascend")
  private Double ascend = null;

  @SerializedName("descend")
  private Double descend = null;

  @SerializedName("points")
  private ResponseCoordinates points = null;

  @SerializedName("points_encoded")
  private Boolean pointsEncoded = null;

  @SerializedName("bbox")
  private List<Double> bbox = new ArrayList<Double>();

  @SerializedName("snapped_waypoints")
  private ResponseCoordinates snappedWaypoints = null;

  @SerializedName("instructions")
  private ResponseInstructions instructions = null;

  public RouteResponsePath distance(Double distance) {
    this.distance = distance;
    return this;
  }

   /**
   * The total distance of the route, in meter
   * @return distance
  **/
  @ApiModelProperty(example = "null", value = "The total distance of the route, in meter")
  public Double getDistance() {
    return distance;
  }

  public void setDistance(Double distance) {
    this.distance = distance;
  }

  public RouteResponsePath time(Long time) {
    this.time = time;
    return this;
  }

   /**
   * The total time of the route, in ms
   * @return time
  **/
  @ApiModelProperty(example = "null", value = "The total time of the route, in ms")
  public Long getTime() {
    return time;
  }

  public void setTime(Long time) {
    this.time = time;
  }

  public RouteResponsePath ascend(Double ascend) {
    this.ascend = ascend;
    return this;
  }

   /**
   * Get ascend
   * @return ascend
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getAscend() {
    return ascend;
  }

  public void setAscend(Double ascend) {
    this.ascend = ascend;
  }

  public RouteResponsePath descend(Double descend) {
    this.descend = descend;
    return this;
  }

   /**
   * The total descend (downhill) of the route, in meter
   * @return descend
  **/
  @ApiModelProperty(example = "null", value = "The total descend (downhill) of the route, in meter")
  public Double getDescend() {
    return descend;
  }

  public void setDescend(Double descend) {
    this.descend = descend;
  }

  public RouteResponsePath points(ResponseCoordinates points) {
    this.points = points;
    return this;
  }

   /**
   * Get points
   * @return points
  **/
  @ApiModelProperty(example = "null", value = "")
  public ResponseCoordinates getPoints() {
    return points;
  }

  public void setPoints(ResponseCoordinates points) {
    this.points = points;
  }

  public RouteResponsePath pointsEncoded(Boolean pointsEncoded) {
    this.pointsEncoded = pointsEncoded;
    return this;
  }

   /**
   * Is true if the points are encoded, if not paths[0].points contains the geo json of the path (then order is lon,lat,elevation), which is easier to handle but consumes more bandwidth compared to encoded version
   * @return pointsEncoded
  **/
  @ApiModelProperty(example = "null", value = "Is true if the points are encoded, if not paths[0].points contains the geo json of the path (then order is lon,lat,elevation), which is easier to handle but consumes more bandwidth compared to encoded version")
  public Boolean getPointsEncoded() {
    return pointsEncoded;
  }

  public void setPointsEncoded(Boolean pointsEncoded) {
    this.pointsEncoded = pointsEncoded;
  }

  public RouteResponsePath bbox(List<Double> bbox) {
    this.bbox = bbox;
    return this;
  }

  public RouteResponsePath addBboxItem(Double bboxItem) {
    this.bbox.add(bboxItem);
    return this;
  }

   /**
   * The bounding box of the route, format <br> minLon, minLat, maxLon, maxLat
   * @return bbox
  **/
  @ApiModelProperty(example = "null", value = "The bounding box of the route, format <br> minLon, minLat, maxLon, maxLat")
  public List<Double> getBbox() {
    return bbox;
  }

  public void setBbox(List<Double> bbox) {
    this.bbox = bbox;
  }

  public RouteResponsePath snappedWaypoints(ResponseCoordinates snappedWaypoints) {
    this.snappedWaypoints = snappedWaypoints;
    return this;
  }

   /**
   * Get snappedWaypoints
   * @return snappedWaypoints
  **/
  @ApiModelProperty(example = "null", value = "")
  public ResponseCoordinates getSnappedWaypoints() {
    return snappedWaypoints;
  }

  public void setSnappedWaypoints(ResponseCoordinates snappedWaypoints) {
    this.snappedWaypoints = snappedWaypoints;
  }

  public RouteResponsePath instructions(ResponseInstructions instructions) {
    this.instructions = instructions;
    return this;
  }

   /**
   * Get instructions
   * @return instructions
  **/
  @ApiModelProperty(example = "null", value = "")
  public ResponseInstructions getInstructions() {
    return instructions;
  }

  public void setInstructions(ResponseInstructions instructions) {
    this.instructions = instructions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RouteResponsePath routeResponsePath = (RouteResponsePath) o;
    return Objects.equals(this.distance, routeResponsePath.distance) &&
        Objects.equals(this.time, routeResponsePath.time) &&
        Objects.equals(this.ascend, routeResponsePath.ascend) &&
        Objects.equals(this.descend, routeResponsePath.descend) &&
        Objects.equals(this.points, routeResponsePath.points) &&
        Objects.equals(this.pointsEncoded, routeResponsePath.pointsEncoded) &&
        Objects.equals(this.bbox, routeResponsePath.bbox) &&
        Objects.equals(this.snappedWaypoints, routeResponsePath.snappedWaypoints) &&
        Objects.equals(this.instructions, routeResponsePath.instructions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(distance, time, ascend, descend, points, pointsEncoded, bbox, snappedWaypoints, instructions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RouteResponsePath {\n");
    
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    ascend: ").append(toIndentedString(ascend)).append("\n");
    sb.append("    descend: ").append(toIndentedString(descend)).append("\n");
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("    pointsEncoded: ").append(toIndentedString(pointsEncoded)).append("\n");
    sb.append("    bbox: ").append(toIndentedString(bbox)).append("\n");
    sb.append("    snappedWaypoints: ").append(toIndentedString(snappedWaypoints)).append("\n");
    sb.append("    instructions: ").append(toIndentedString(instructions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

