=begin comment

GraphHopper Directions API

You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::SwaggerClient::RoutingApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::SwaggerClient::ApiClient;
use WWW::SwaggerClient::Configuration;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class   = shift;
    my (%self) = (
        'api_client' => WWW::SwaggerClient::ApiClient->instance,
        @_
    );

    #my $self = {
    #    #api_client => $options->{api_client}
    #    api_client => $default_api_client
    #}; 

    bless \%self, $class;

}


#
# route_get
#
# Routing Request
# 
# @param ARRAY[string] $point Specify multiple points for which the route should be calculated. The order is important. Specify at least two points. (required)
# @param boolean $points_encoded IMPORTANT- TODO - currently you have to pass false for the swagger client - Have not found a way to force add a parameter. If &#x60;false&#x60; the coordinates in &#x60;point&#x60; and &#x60;snapped_waypoints&#x60; are returned as array using the order [lon,lat,elevation] for every point. If &#x60;true&#x60; the coordinates will be encoded as string leading to less bandwith usage. You&#39;ll need a special handling for the decoding of this string on the client-side. We provide open source code in [Java](https://github.com/graphhopper/graphhopper/blob/d70b63660ac5200b03c38ba3406b8f93976628a6/web/src/main/java/com/graphhopper/http/WebHelper.java#L43) and [JavaScript](https://github.com/graphhopper/graphhopper/blob/d70b63660ac5200b03c38ba3406b8f93976628a6/web/src/main/webapp/js/ghrequest.js#L139). It is especially important to use no 3rd party client if you set &#x60;elevation&#x3D;true&#x60;! (required)
# @param string $key Get your key at graphhopper.com (required)
# @param string $locale The locale of the resulting turn instructions. E.g. &#x60;pt_PT&#x60; for Portuguese or &#x60;de&#x60; for German (optional)
# @param boolean $instructions If instruction should be calculated and returned (optional)
# @param string $vehicle The vehicle for which the route should be calculated. Other vehicles are foot, small_truck, ... (optional)
# @param boolean $elevation If &#x60;true&#x60; a third dimension - the elevation - is included in the polyline or in the GeoJson. If enabled you have to use a modified version of the decoding method or set points_encoded to &#x60;false&#x60;. See the points_encoded attribute for more details. Additionally a request can fail if the vehicle does not support elevation. See the features object for every vehicle. (optional)
# @param boolean $calc_points If the points for the route should be calculated at all printing out only distance and time. (optional)
# @param ARRAY[string] $point_hint Optional parameter. Specifies a hint for each &#x60;point&#x60; parameter to prefer a certain street for the closest location lookup. E.g. if there is an address or house with two or more neighboring streets you can control for which street the closest location is looked up. (optional)
# @param boolean $ch/disable Use this parameter in combination with one or more parameters of this table (optional)
# @param string $weighting Which kind of &#39;best&#39; route calculation you need. Other option is &#x60;shortest&#x60; (e.g. for &#x60;vehicle&#x3D;foot&#x60; or &#x60;bike&#x60;), &#x60;short_fastest&#x60; if time and distance is expensive e.g. for &#x60;vehicle&#x3D;truck&#x60; (optional)
# @param boolean $edge_traversal Use &#x60;true&#x60; if you want to consider turn restrictions for bike and motor vehicles. Keep in mind that the response time is roughly 2 times slower. (optional)
# @param string $algorithm The algorithm to calculate the route. Other options are &#x60;dijkstra&#x60;, &#x60;astar&#x60;, &#x60;astarbi&#x60;, &#x60;alternative_route&#x60; and &#x60;round_trip&#x60; (optional)
# @param int $heading Favour a heading direction for a certain point. Specify either one heading for the start point or as many as there are points. In this case headings are associated by their order to the specific points. Headings are given as north based clockwise angle between 0 and 360 degree. This parameter also influences the tour generated with &#x60;algorithm&#x3D;round_trip&#x60; and force the initial direction. (optional)
# @param int $heading_penalty Penalty for omitting a specified heading. The penalty corresponds to the accepted time delay in seconds in comparison to the route without a heading. (optional)
# @param boolean $pass_through If &#x60;true&#x60; u-turns are avoided at via-points with regard to the &#x60;heading_penalty&#x60;. (optional)
# @param int $round_trip/distance If &#x60;algorithm&#x3D;round_trip&#x60; this parameter configures approximative length of the resulting round trip (optional)
# @param int $round_trip/seed If &#x60;algorithm&#x3D;round_trip&#x60; this parameter introduces randomness if e.g. the first try wasn&#39;t good. (optional)
# @param int $alternative_route/max_paths If &#x60;algorithm&#x3D;alternative_route&#x60; this parameter sets the number of maximum paths which should be calculated. Increasing can lead to worse alternatives. (optional)
# @param int $alternative_route/max_weight_factor If &#x60;algorithm&#x3D;alternative_route&#x60; this parameter sets the factor by which the alternatives routes can be longer than the optimal route. Increasing can lead to worse alternatives. (optional)
# @param int $alternative_route/max_share_factor If &#x60;algorithm&#x3D;alternative_route&#x60; this parameter specifies how much alternatives routes can have maximum in common with the optimal route. Increasing can lead to worse alternatives. (optional)
{
    my $params = {
    'point' => {
        data_type => 'ARRAY[string]',
        description => 'Specify multiple points for which the route should be calculated. The order is important. Specify at least two points.',
        required => '1',
    },
    'points_encoded' => {
        data_type => 'boolean',
        description => 'IMPORTANT- TODO - currently you have to pass false for the swagger client - Have not found a way to force add a parameter. If &#x60;false&#x60; the coordinates in &#x60;point&#x60; and &#x60;snapped_waypoints&#x60; are returned as array using the order [lon,lat,elevation] for every point. If &#x60;true&#x60; the coordinates will be encoded as string leading to less bandwith usage. You&#39;ll need a special handling for the decoding of this string on the client-side. We provide open source code in [Java](https://github.com/graphhopper/graphhopper/blob/d70b63660ac5200b03c38ba3406b8f93976628a6/web/src/main/java/com/graphhopper/http/WebHelper.java#L43) and [JavaScript](https://github.com/graphhopper/graphhopper/blob/d70b63660ac5200b03c38ba3406b8f93976628a6/web/src/main/webapp/js/ghrequest.js#L139). It is especially important to use no 3rd party client if you set &#x60;elevation&#x3D;true&#x60;!',
        required => '1',
    },
    'key' => {
        data_type => 'string',
        description => 'Get your key at graphhopper.com',
        required => '1',
    },
    'locale' => {
        data_type => 'string',
        description => 'The locale of the resulting turn instructions. E.g. &#x60;pt_PT&#x60; for Portuguese or &#x60;de&#x60; for German',
        required => '0',
    },
    'instructions' => {
        data_type => 'boolean',
        description => 'If instruction should be calculated and returned',
        required => '0',
    },
    'vehicle' => {
        data_type => 'string',
        description => 'The vehicle for which the route should be calculated. Other vehicles are foot, small_truck, ...',
        required => '0',
    },
    'elevation' => {
        data_type => 'boolean',
        description => 'If &#x60;true&#x60; a third dimension - the elevation - is included in the polyline or in the GeoJson. If enabled you have to use a modified version of the decoding method or set points_encoded to &#x60;false&#x60;. See the points_encoded attribute for more details. Additionally a request can fail if the vehicle does not support elevation. See the features object for every vehicle.',
        required => '0',
    },
    'calc_points' => {
        data_type => 'boolean',
        description => 'If the points for the route should be calculated at all printing out only distance and time.',
        required => '0',
    },
    'point_hint' => {
        data_type => 'ARRAY[string]',
        description => 'Optional parameter. Specifies a hint for each &#x60;point&#x60; parameter to prefer a certain street for the closest location lookup. E.g. if there is an address or house with two or more neighboring streets you can control for which street the closest location is looked up.',
        required => '0',
    },
    'ch/disable' => {
        data_type => 'boolean',
        description => 'Use this parameter in combination with one or more parameters of this table',
        required => '0',
    },
    'weighting' => {
        data_type => 'string',
        description => 'Which kind of &#39;best&#39; route calculation you need. Other option is &#x60;shortest&#x60; (e.g. for &#x60;vehicle&#x3D;foot&#x60; or &#x60;bike&#x60;), &#x60;short_fastest&#x60; if time and distance is expensive e.g. for &#x60;vehicle&#x3D;truck&#x60;',
        required => '0',
    },
    'edge_traversal' => {
        data_type => 'boolean',
        description => 'Use &#x60;true&#x60; if you want to consider turn restrictions for bike and motor vehicles. Keep in mind that the response time is roughly 2 times slower.',
        required => '0',
    },
    'algorithm' => {
        data_type => 'string',
        description => 'The algorithm to calculate the route. Other options are &#x60;dijkstra&#x60;, &#x60;astar&#x60;, &#x60;astarbi&#x60;, &#x60;alternative_route&#x60; and &#x60;round_trip&#x60;',
        required => '0',
    },
    'heading' => {
        data_type => 'int',
        description => 'Favour a heading direction for a certain point. Specify either one heading for the start point or as many as there are points. In this case headings are associated by their order to the specific points. Headings are given as north based clockwise angle between 0 and 360 degree. This parameter also influences the tour generated with &#x60;algorithm&#x3D;round_trip&#x60; and force the initial direction.',
        required => '0',
    },
    'heading_penalty' => {
        data_type => 'int',
        description => 'Penalty for omitting a specified heading. The penalty corresponds to the accepted time delay in seconds in comparison to the route without a heading.',
        required => '0',
    },
    'pass_through' => {
        data_type => 'boolean',
        description => 'If &#x60;true&#x60; u-turns are avoided at via-points with regard to the &#x60;heading_penalty&#x60;.',
        required => '0',
    },
    'round_trip/distance' => {
        data_type => 'int',
        description => 'If &#x60;algorithm&#x3D;round_trip&#x60; this parameter configures approximative length of the resulting round trip',
        required => '0',
    },
    'round_trip/seed' => {
        data_type => 'int',
        description => 'If &#x60;algorithm&#x3D;round_trip&#x60; this parameter introduces randomness if e.g. the first try wasn&#39;t good.',
        required => '0',
    },
    'alternative_route/max_paths' => {
        data_type => 'int',
        description => 'If &#x60;algorithm&#x3D;alternative_route&#x60; this parameter sets the number of maximum paths which should be calculated. Increasing can lead to worse alternatives.',
        required => '0',
    },
    'alternative_route/max_weight_factor' => {
        data_type => 'int',
        description => 'If &#x60;algorithm&#x3D;alternative_route&#x60; this parameter sets the factor by which the alternatives routes can be longer than the optimal route. Increasing can lead to worse alternatives.',
        required => '0',
    },
    'alternative_route/max_share_factor' => {
        data_type => 'int',
        description => 'If &#x60;algorithm&#x3D;alternative_route&#x60; this parameter specifies how much alternatives routes can have maximum in common with the optimal route. Increasing can lead to worse alternatives.',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'route_get' } = { 
    	summary => 'Routing Request',
        params => $params,
        returns => 'RouteResponse',
        };
}
# @return RouteResponse
#
sub route_get {
    my ($self, %args) = @_;

    # verify the required parameter 'point' is set
    unless (exists $args{'point'}) {
      croak("Missing the required parameter 'point' when calling route_get");
    }

    # verify the required parameter 'points_encoded' is set
    unless (exists $args{'points_encoded'}) {
      croak("Missing the required parameter 'points_encoded' when calling route_get");
    }

    # verify the required parameter 'key' is set
    unless (exists $args{'key'}) {
      croak("Missing the required parameter 'key' when calling route_get");
    }

    # parse inputs
    my $_resource_path = '/route';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'point'}) {
        $query_params->{'point'} = $self->{api_client}->to_query_value($args{'point'});
    }

    # query params
    if ( exists $args{'locale'}) {
        $query_params->{'locale'} = $self->{api_client}->to_query_value($args{'locale'});
    }

    # query params
    if ( exists $args{'instructions'}) {
        $query_params->{'instructions'} = $self->{api_client}->to_query_value($args{'instructions'});
    }

    # query params
    if ( exists $args{'vehicle'}) {
        $query_params->{'vehicle'} = $self->{api_client}->to_query_value($args{'vehicle'});
    }

    # query params
    if ( exists $args{'elevation'}) {
        $query_params->{'elevation'} = $self->{api_client}->to_query_value($args{'elevation'});
    }

    # query params
    if ( exists $args{'points_encoded'}) {
        $query_params->{'points_encoded'} = $self->{api_client}->to_query_value($args{'points_encoded'});
    }

    # query params
    if ( exists $args{'calc_points'}) {
        $query_params->{'calc_points'} = $self->{api_client}->to_query_value($args{'calc_points'});
    }

    # query params
    if ( exists $args{'point_hint'}) {
        $query_params->{'point_hint'} = $self->{api_client}->to_query_value($args{'point_hint'});
    }

    # query params
    if ( exists $args{'ch/disable'}) {
        $query_params->{'ch.disable'} = $self->{api_client}->to_query_value($args{'ch/disable'});
    }

    # query params
    if ( exists $args{'weighting'}) {
        $query_params->{'weighting'} = $self->{api_client}->to_query_value($args{'weighting'});
    }

    # query params
    if ( exists $args{'edge_traversal'}) {
        $query_params->{'edge_traversal'} = $self->{api_client}->to_query_value($args{'edge_traversal'});
    }

    # query params
    if ( exists $args{'algorithm'}) {
        $query_params->{'algorithm'} = $self->{api_client}->to_query_value($args{'algorithm'});
    }

    # query params
    if ( exists $args{'heading'}) {
        $query_params->{'heading'} = $self->{api_client}->to_query_value($args{'heading'});
    }

    # query params
    if ( exists $args{'heading_penalty'}) {
        $query_params->{'heading_penalty'} = $self->{api_client}->to_query_value($args{'heading_penalty'});
    }

    # query params
    if ( exists $args{'pass_through'}) {
        $query_params->{'pass_through'} = $self->{api_client}->to_query_value($args{'pass_through'});
    }

    # query params
    if ( exists $args{'round_trip/distance'}) {
        $query_params->{'round_trip.distance'} = $self->{api_client}->to_query_value($args{'round_trip/distance'});
    }

    # query params
    if ( exists $args{'round_trip/seed'}) {
        $query_params->{'round_trip.seed'} = $self->{api_client}->to_query_value($args{'round_trip/seed'});
    }

    # query params
    if ( exists $args{'alternative_route/max_paths'}) {
        $query_params->{'alternative_route.max_paths'} = $self->{api_client}->to_query_value($args{'alternative_route/max_paths'});
    }

    # query params
    if ( exists $args{'alternative_route/max_weight_factor'}) {
        $query_params->{'alternative_route.max_weight_factor'} = $self->{api_client}->to_query_value($args{'alternative_route/max_weight_factor'});
    }

    # query params
    if ( exists $args{'alternative_route/max_share_factor'}) {
        $query_params->{'alternative_route.max_share_factor'} = $self->{api_client}->to_query_value($args{'alternative_route/max_share_factor'});
    }

    # query params
    if ( exists $args{'key'}) {
        $query_params->{'key'} = $self->{api_client}->to_query_value($args{'key'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('RouteResponse', $response);
    return $_response_object;
}

1;
