/**
 * GraphHopper Directions API
 * With the GraphHopper Directions API you get reliable and fast web services for routing and more with world wide coverage. We offer A-to-B routing via the Routing API optionally with turn instructions and elevation data as well as route optimization with various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGBreak.h
 * 
 * 
 */

#ifndef SWGBreak_H_
#define SWGBreak_H_

#include <QJsonObject>


#include <QList>

#include "SWGObject.h"


namespace Swagger {

class SWGBreak: public SWGObject {
public:
    SWGBreak();
    SWGBreak(QString* json);
    virtual ~SWGBreak();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGBreak* fromJson(QString &jsonString);

    qint64 getEarliest();
    void setEarliest(qint64 earliest);

    qint64 getLatest();
    void setLatest(qint64 latest);

    qint64 getDuration();
    void setDuration(qint64 duration);

    qint64 getMaxDrivingTime();
    void setMaxDrivingTime(qint64 max_driving_time);

    qint64 getInitialDrivingTime();
    void setInitialDrivingTime(qint64 initial_driving_time);

    QList<qint64>* getPossibleSplit();
    void setPossibleSplit(QList<qint64>* possible_split);


private:
    qint64 earliest;
    qint64 latest;
    qint64 duration;
    qint64 max_driving_time;
    qint64 initial_driving_time;
    QList<qint64>* possible_split;
};

} /* namespace Swagger */

#endif /* SWGBreak_H_ */
