/**
 * GraphHopper Directions API
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGCostMatrix.h
 * 
 * 
 */

#ifndef SWGCostMatrix_H_
#define SWGCostMatrix_H_

#include <QJsonObject>


#include "SWGCostMatrix_data.h"
#include <QList>
#include <QString>

#include "SWGObject.h"

namespace Swagger {

class SWGCostMatrix: public SWGObject {
public:
    SWGCostMatrix();
    SWGCostMatrix(QString* json);
    virtual ~SWGCostMatrix();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGCostMatrix* fromJson(QString &jsonString);

    QString* getType();
    void setType(QString* type);

    QString* getUrl();
    void setUrl(QString* url);

    QList<QString*>* getLocationIds();
    void setLocationIds(QList<QString*>* location_ids);

    SWGCostMatrix_data* getData();
    void setData(SWGCostMatrix_data* data);

    QString* getProfile();
    void setProfile(QString* profile);


    virtual bool isSet() override;

private:
    QString* type;
    bool m_type_isSet;
    
    QString* url;
    bool m_url_isSet;
    
    QList<QString*>* location_ids;
    bool m_location_ids_isSet;
    
    SWGCostMatrix_data* data;
    bool m_data_isSet;
    
    QString* profile;
    bool m_profile_isSet;
    
};

}

#endif /* SWGCostMatrix_H_ */
