/**
 * GraphHopper Directions API
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGCostMatrix_data.h
 * 
 * JSON data of matrix response
 */

#ifndef SWGCostMatrix_data_H_
#define SWGCostMatrix_data_H_

#include <QJsonObject>


#include "SWGCostMatrix_data_info.h"
#include <QList>

#include "SWGObject.h"


namespace Swagger {

class SWGCostMatrix_data: public SWGObject {
public:
    SWGCostMatrix_data();
    SWGCostMatrix_data(QString* json);
    virtual ~SWGCostMatrix_data();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGCostMatrix_data* fromJson(QString &jsonString);

    QList<QList<qint64>*>* getTimes();
    void setTimes(QList<QList<qint64>*>* times);

    QList<QList<double>*>* getDistances();
    void setDistances(QList<QList<double>*>* distances);

    SWGCostMatrix_data_info* getInfo();
    void setInfo(SWGCostMatrix_data_info* info);


private:
    QList<QList<qint64>*>* times;
    QList<QList<double>*>* distances;
    SWGCostMatrix_data_info* info;
};

}

#endif /* SWGCostMatrix_data_H_ */
