/**
 * GraphHopper Directions API
 * With the GraphHopper Directions API you get reliable and fast web services for routing and more with world wide coverage. We offer A-to-B routing via the Routing API optionally with turn instructions and elevation data as well as route optimization with various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "SWGIsochroneApi.h"
#include "SWGHelpers.h"
#include "SWGModelFactory.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace Swagger {
SWGIsochroneApi::SWGIsochroneApi() {}

SWGIsochroneApi::~SWGIsochroneApi() {}

SWGIsochroneApi::SWGIsochroneApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
SWGIsochroneApi::isochroneGet(QString* point, QString* key, qint32 time_limit, QString* vehicle, qint32 buckets, bool reverse_flow) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/isochrone");


    if (fullPath.indexOf("?") > 0) 
      fullPath.append("&");
    else 
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("point"))
        .append("=")
        .append(QUrl::toPercentEncoding(stringValue(point)));

    if (fullPath.indexOf("?") > 0) 
      fullPath.append("&");
    else 
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("time_limit"))
        .append("=")
        .append(QUrl::toPercentEncoding(stringValue(time_limit)));

    if (fullPath.indexOf("?") > 0) 
      fullPath.append("&");
    else 
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("vehicle"))
        .append("=")
        .append(QUrl::toPercentEncoding(stringValue(vehicle)));

    if (fullPath.indexOf("?") > 0) 
      fullPath.append("&");
    else 
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("buckets"))
        .append("=")
        .append(QUrl::toPercentEncoding(stringValue(buckets)));

    if (fullPath.indexOf("?") > 0) 
      fullPath.append("&");
    else 
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("reverse_flow"))
        .append("=")
        .append(QUrl::toPercentEncoding(stringValue(reverse_flow)));

    if (fullPath.indexOf("?") > 0) 
      fullPath.append("&");
    else 
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("key"))
        .append("=")
        .append(QUrl::toPercentEncoding(stringValue(key)));


    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "GET");

    



    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGIsochroneApi::isochroneGetCallback);

    worker->execute(&input);
}

void
SWGIsochroneApi::isochroneGetCallback(HttpRequestWorker * worker) {
    QString msg;
    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    
        QString json(worker->response);
    SWGGHIsochroneResponse* output = static_cast<SWGGHIsochroneResponse*>(create(json, QString("SWGGHIsochroneResponse")));
    

    worker->deleteLater();

    emit isochroneGetSignal(output);
    
}
} /* namespace Swagger */
