/**
 * GraphHopper Directions API
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGLocation.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGLocation::SWGLocation(QString* json) {
    init();
    this->fromJson(*json);
}

SWGLocation::SWGLocation() {
    init();
}

SWGLocation::~SWGLocation() {
    this->cleanup();
}

void
SWGLocation::init() {
    lon = 0.0;
    lat = 0.0;
}

void
SWGLocation::cleanup() {
    

}

SWGLocation*
SWGLocation::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGLocation::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&lon, pJson["lon"], "double", "");
    ::Swagger::setValue(&lat, pJson["lat"], "double", "");
}

QString
SWGLocation::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGLocation::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    obj->insert("lon", QJsonValue(lon));

    obj->insert("lat", QJsonValue(lat));

    return obj;
}

double
SWGLocation::getLon() {
    return lon;
}
void
SWGLocation::setLon(double lon) {
    this->lon = lon;
}

double
SWGLocation::getLat() {
    return lat;
}
void
SWGLocation::setLat(double lat) {
    this->lat = lat;
}


}

