/**
 * GraphHopper Directions API
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGObjective.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGObjective::SWGObjective(QString* json) {
    init();
    this->fromJson(*json);
}

SWGObjective::SWGObjective() {
    init();
}

SWGObjective::~SWGObjective() {
    this->cleanup();
}

void
SWGObjective::init() {
    type = new QString("");
    value = new QString("");
}

void
SWGObjective::cleanup() {
    
    if(type != nullptr) {
        delete type;
    }

    if(value != nullptr) {
        delete value;
    }
}

SWGObjective*
SWGObjective::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGObjective::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&type, pJson["type"], "QString", "QString");
    ::Swagger::setValue(&value, pJson["value"], "QString", "QString");
}

QString
SWGObjective::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGObjective::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    toJsonValue(QString("type"), type, obj, QString("QString"));

    toJsonValue(QString("value"), value, obj, QString("QString"));

    return obj;
}

QString*
SWGObjective::getType() {
    return type;
}
void
SWGObjective::setType(QString* type) {
    this->type = type;
}

QString*
SWGObjective::getValue() {
    return value;
}
void
SWGObjective::setValue(QString* value) {
    this->value = value;
}


}

