/**
 * GraphHopper Directions API
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGRouteResponsePath.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGRouteResponsePath::SWGRouteResponsePath(QString* json) {
    init();
    this->fromJson(*json);
}

SWGRouteResponsePath::SWGRouteResponsePath() {
    init();
}

SWGRouteResponsePath::~SWGRouteResponsePath() {
    this->cleanup();
}

void
SWGRouteResponsePath::init() {
    distance = 0.0;
    m_distance_isSet = false;
    time = 0L;
    m_time_isSet = false;
    ascend = 0.0;
    m_ascend_isSet = false;
    descend = 0.0;
    m_descend_isSet = false;
    points = new SWGResponseCoordinates();
    m_points_isSet = false;
    points_encoded = false;
    m_points_encoded_isSet = false;
    bbox = new QList<double>();
    m_bbox_isSet = false;
    snapped_waypoints = new SWGResponseCoordinates();
    m_snapped_waypoints_isSet = false;
    instructions = new SWGResponseInstructions();
    m_instructions_isSet = false;
}

void
SWGRouteResponsePath::cleanup() {




    if(points != nullptr) { 
        delete points;
    }


    if(snapped_waypoints != nullptr) { 
        delete snapped_waypoints;
    }
    if(instructions != nullptr) { 
        delete instructions;
    }
}

SWGRouteResponsePath*
SWGRouteResponsePath::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGRouteResponsePath::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&distance, pJson["distance"], "double", "");
    
    ::Swagger::setValue(&time, pJson["time"], "qint64", "");
    
    ::Swagger::setValue(&ascend, pJson["ascend"], "double", "");
    
    ::Swagger::setValue(&descend, pJson["descend"], "double", "");
    
    ::Swagger::setValue(&points, pJson["points"], "SWGResponseCoordinates", "SWGResponseCoordinates");
    
    ::Swagger::setValue(&points_encoded, pJson["points_encoded"], "bool", "");
    
    
    ::Swagger::setValue(&bbox, pJson["bbox"], "QList", "double");
    ::Swagger::setValue(&snapped_waypoints, pJson["snapped_waypoints"], "SWGResponseCoordinates", "SWGResponseCoordinates");
    
    ::Swagger::setValue(&instructions, pJson["instructions"], "SWGResponseInstructions", "SWGResponseInstructions");
    
}

QString
SWGRouteResponsePath::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGRouteResponsePath::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    if(m_distance_isSet){
        obj->insert("distance", QJsonValue(distance));
    }
    
    if(m_time_isSet){
        obj->insert("time", QJsonValue(time));
    }
    
    if(m_ascend_isSet){
        obj->insert("ascend", QJsonValue(ascend));
    }
    
    if(m_descend_isSet){
        obj->insert("descend", QJsonValue(descend));
    }
     
    if((points != nullptr) && (points->isSet())){
        toJsonValue(QString("points"), points, obj, QString("SWGResponseCoordinates"));
    }
    
    if(m_points_encoded_isSet){
        obj->insert("points_encoded", QJsonValue(points_encoded));
    }
    
    if(bbox->size() > 0){
        toJsonArray((QList<void*>*)bbox, obj, "bbox", "");
    }
     
    if((snapped_waypoints != nullptr) && (snapped_waypoints->isSet())){
        toJsonValue(QString("snapped_waypoints"), snapped_waypoints, obj, QString("SWGResponseCoordinates"));
    }
     
    if((instructions != nullptr) && (instructions->isSet())){
        toJsonValue(QString("instructions"), instructions, obj, QString("SWGResponseInstructions"));
    }

    return obj;
}

double
SWGRouteResponsePath::getDistance() {
    return distance;
}
void
SWGRouteResponsePath::setDistance(double distance) {
    this->distance = distance;
    this->m_distance_isSet = true;
}

qint64
SWGRouteResponsePath::getTime() {
    return time;
}
void
SWGRouteResponsePath::setTime(qint64 time) {
    this->time = time;
    this->m_time_isSet = true;
}

double
SWGRouteResponsePath::getAscend() {
    return ascend;
}
void
SWGRouteResponsePath::setAscend(double ascend) {
    this->ascend = ascend;
    this->m_ascend_isSet = true;
}

double
SWGRouteResponsePath::getDescend() {
    return descend;
}
void
SWGRouteResponsePath::setDescend(double descend) {
    this->descend = descend;
    this->m_descend_isSet = true;
}

SWGResponseCoordinates*
SWGRouteResponsePath::getPoints() {
    return points;
}
void
SWGRouteResponsePath::setPoints(SWGResponseCoordinates* points) {
    this->points = points;
    this->m_points_isSet = true;
}

bool
SWGRouteResponsePath::isPointsEncoded() {
    return points_encoded;
}
void
SWGRouteResponsePath::setPointsEncoded(bool points_encoded) {
    this->points_encoded = points_encoded;
    this->m_points_encoded_isSet = true;
}

QList<double>*
SWGRouteResponsePath::getBbox() {
    return bbox;
}
void
SWGRouteResponsePath::setBbox(QList<double>* bbox) {
    this->bbox = bbox;
    this->m_bbox_isSet = true;
}

SWGResponseCoordinates*
SWGRouteResponsePath::getSnappedWaypoints() {
    return snapped_waypoints;
}
void
SWGRouteResponsePath::setSnappedWaypoints(SWGResponseCoordinates* snapped_waypoints) {
    this->snapped_waypoints = snapped_waypoints;
    this->m_snapped_waypoints_isSet = true;
}

SWGResponseInstructions*
SWGRouteResponsePath::getInstructions() {
    return instructions;
}
void
SWGRouteResponsePath::setInstructions(SWGResponseInstructions* instructions) {
    this->instructions = instructions;
    this->m_instructions_isSet = true;
}


bool 
SWGRouteResponsePath::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_distance_isSet){ isObjectUpdated = true; break;}
        if(m_time_isSet){ isObjectUpdated = true; break;}
        if(m_ascend_isSet){ isObjectUpdated = true; break;}
        if(m_descend_isSet){ isObjectUpdated = true; break;}
        if(points != nullptr && points->isSet()){ isObjectUpdated = true; break;}
        if(m_points_encoded_isSet){ isObjectUpdated = true; break;}
        if(m_bbox_isSet){ isObjectUpdated = true; break;}if(bbox->size() > 0){ isObjectUpdated = true; break;}
        if(snapped_waypoints != nullptr && snapped_waypoints->isSet()){ isObjectUpdated = true; break;}
        if(instructions != nullptr && instructions->isSet()){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

