/**
 * GraphHopper Directions API
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGRelation.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {

SWGRelation::SWGRelation(QString* json) {
    init();
    this->fromJson(*json);
}

SWGRelation::SWGRelation() {
    init();
}

SWGRelation::~SWGRelation() {
    this->cleanup();
}

void
SWGRelation::init() {
    type = new QString("");
    m_type_isSet = false;
    ids = new QList<QString*>();
    m_ids_isSet = false;
    vehicle_id = new QString("");
    m_vehicle_id_isSet = false;
}

void
SWGRelation::cleanup() {
    if(type != nullptr) { 
        delete type;
    }
    if(ids != nullptr) { 
        auto arr = ids;
        for(auto o: *arr) { 
            delete o;
        }
        delete ids;
    }
    if(vehicle_id != nullptr) { 
        delete vehicle_id;
    }
}

SWGRelation*
SWGRelation::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGRelation::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&type, pJson["type"], "QString", "QString");
    
    
    ::Swagger::setValue(&ids, pJson["ids"], "QList", "QString");
    ::Swagger::setValue(&vehicle_id, pJson["vehicle_id"], "QString", "QString");
    
}

QString
SWGRelation::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGRelation::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    if(type != nullptr && *type != QString("")){
        toJsonValue(QString("type"), type, obj, QString("QString"));
    }
    
    if(ids->size() > 0){
        toJsonArray((QList<void*>*)ids, obj, "ids", "QString");
    }
    
    if(vehicle_id != nullptr && *vehicle_id != QString("")){
        toJsonValue(QString("vehicle_id"), vehicle_id, obj, QString("QString"));
    }

    return obj;
}

QString*
SWGRelation::getType() {
    return type;
}
void
SWGRelation::setType(QString* type) {
    this->type = type;
    this->m_type_isSet = true;
}

QList<QString*>*
SWGRelation::getIds() {
    return ids;
}
void
SWGRelation::setIds(QList<QString*>* ids) {
    this->ids = ids;
    this->m_ids_isSet = true;
}

QString*
SWGRelation::getVehicleId() {
    return vehicle_id;
}
void
SWGRelation::setVehicleId(QString* vehicle_id) {
    this->vehicle_id = vehicle_id;
    this->m_vehicle_id_isSet = true;
}


bool 
SWGRelation::isSet(){
    bool isObjectUpdated = false;
    do{
        if(type != nullptr && *type != QString("")){ isObjectUpdated = true; break;}
        if(ids->size() > 0){ isObjectUpdated = true; break;}
        if(vehicle_id != nullptr && *vehicle_id != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

