//
// Solution.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Solution: JSONEncodable {
    /** overall costs of solution */
    public var costs: Int32?
    /** overall travel distance in meters */
    public var distance: Int32?
    /** overall transport time in seconds */
    public var time: Int64?
    /** overall transport time in seconds */
    public var transportTime: Int64?
    /** operation time of the longest route in seconds */
    public var maxOperationTime: Int64?
    /** total waiting time in seconds */
    public var waitingTime: Int64?
    /** total service time in seconds */
    public var serviceDuration: Int64?
    /** total preparation time in seconds */
    public var preparationTime: Int64?
    /** total completion time in seconds */
    public var completionTime: Int64?
    /** number of employed vehicles */
    public var noVehicles: Int32?
    /** number of jobs that could not be assigned to final solution */
    public var noUnassigned: Int32?
    /** An array of routes */
    public var routes: [Route]?
    public var unassigned: SolutionUnassigned?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["costs"] = self.costs?.encodeToJSON()
        nillableDictionary["distance"] = self.distance?.encodeToJSON()
        nillableDictionary["time"] = self.time?.encodeToJSON()
        nillableDictionary["transport_time"] = self.transportTime?.encodeToJSON()
        nillableDictionary["max_operation_time"] = self.maxOperationTime?.encodeToJSON()
        nillableDictionary["waiting_time"] = self.waitingTime?.encodeToJSON()
        nillableDictionary["service_duration"] = self.serviceDuration?.encodeToJSON()
        nillableDictionary["preparation_time"] = self.preparationTime?.encodeToJSON()
        nillableDictionary["completion_time"] = self.completionTime?.encodeToJSON()
        nillableDictionary["no_vehicles"] = self.noVehicles?.encodeToJSON()
        nillableDictionary["no_unassigned"] = self.noUnassigned?.encodeToJSON()
        nillableDictionary["routes"] = self.routes?.encodeToJSON()
        nillableDictionary["unassigned"] = self.unassigned?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
