/*
 * GraphHopper Directions API
 *
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package graphhopper

// A found path
type RouteResponsePath struct {
	// The total distance of the route, in meter
	Distance float64 `json:"distance,omitempty"`

	// The total time of the route, in ms
	Time int64 `json:"time,omitempty"`

	Ascend float64 `json:"ascend,omitempty"`

	// The total descend (downhill) of the route, in meter
	Descend float64 `json:"descend,omitempty"`

	Points *ResponseCoordinates `json:"points,omitempty"`

	// Is true if the points are encoded, if not paths[0].points contains the geo json of the path (then order is lon,lat,elevation), which is easier to handle but consumes more bandwidth compared to encoded version
	PointsEncoded bool `json:"points_encoded,omitempty"`

	// The bounding box of the route, format <br> minLon, minLat, maxLon, maxLat
	Bbox []float64 `json:"bbox,omitempty"`

	SnappedWaypoints *ResponseCoordinates `json:"snapped_waypoints,omitempty"`

	Instructions *ResponseInstructions `json:"instructions,omitempty"`
}
