/* 
 * GraphHopper Directions API
 *
 * With the GraphHopper Directions API you get reliable and fast web services for routing and more with world wide coverage. We offer A-to-B routing via the Routing API optionally with turn instructions and elevation data as well as route optimization with various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package graphhopper

type ModelBreak struct {

	// earliest start of break
	Earliest int64 `json:"earliest,omitempty"`

	// latest start of break
	Latest int64 `json:"latest,omitempty"`

	// duration of break
	Duration int64 `json:"duration,omitempty"`

	// max driving time without break
	MaxDrivingTime int64 `json:"max_driving_time,omitempty"`

	// initial driving time, i.e. the time your driver has already spent for driving
	InitialDrivingTime int64 `json:"initial_driving_time,omitempty"`

	// array of splits
	PossibleSplit []int64 `json:"possible_split,omitempty"`
}
