/*
 * GraphHopper Directions API
 *
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package graphhopper

type Address struct {
	// Unique identifier of location
	LocationId string `json:"location_id,omitempty"`

	// name of location, e.g. street name plus house number
	Name string `json:"name,omitempty"`

	// longitude
	Lon float64 `json:"lon,omitempty"`

	// latitude
	Lat float64 `json:"lat,omitempty"`
}
