//
// Stop.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Stop: Codable {


    public var address: Address?

    /** Specifies the duration of the pickup or delivery in seconds, e.g. how long it takes unload items at the customer site. */
    public var duration: Int64?

    /** Specifies the preparation time in seconds. It can be used to model parking lot search time since if you have 3 identical locations in a row, it only falls due once. */
    public var preparationTime: Int64?

    /** Specifies an array of time window objects (see time window object below). For example, if an item needs to be delivered between 7am and 10am then specify the array as follows: [ { \&quot;earliest\&quot;: 25200, \&quot;latest\&quot; : 32400 } ] (starting the day from 0 in seconds). */
    public var timeWindows: [TimeWindow]?

    /** Group this stop belongs to */
    public var group: String?
    public init(address: Address?, duration: Int64?, preparationTime: Int64?, timeWindows: [TimeWindow]?, group: String?) { 
        self.address = address
        self.duration = duration
        self.preparationTime = preparationTime
        self.timeWindows = timeWindows
        self.group = group
    }
    public enum CodingKeys: String, CodingKey { 
        case address
        case duration
        case preparationTime = "preparation_time"
        case timeWindows = "time_windows"
        case group
    }

}
