//
// TimeWindowBreak.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct TimeWindowBreak: Codable {


    /** Specifies the earliest start time of the break in seconds. */
    public var earliest: Int64

    /** Specifies the latest start time of break in seconds. */
    public var latest: Int64

    /** Specifies the duration of the break in seconds. */
    public var duration: Int64
    public init(earliest: Int64, latest: Int64, duration: Int64) { 
        self.earliest = earliest
        self.latest = latest
        self.duration = duration
    }

}
