/* 
 * GraphHopper Directions API
 *
 * You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Break
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BreakTests
    {
        // TODO uncomment below to declare an instance variable for Break
        //private Break instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Break
            //instance = new Break();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Break
        /// </summary>
        [Test]
        public void BreakInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Break
            //Assert.IsInstanceOfType<Break> (instance, "variable 'instance' is a Break");
        }


        /// <summary>
        /// Test the property 'Earliest'
        /// </summary>
        [Test]
        public void EarliestTest()
        {
            // TODO unit test for the property 'Earliest'
        }
        /// <summary>
        /// Test the property 'Latest'
        /// </summary>
        [Test]
        public void LatestTest()
        {
            // TODO unit test for the property 'Latest'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'MaxDrivingTime'
        /// </summary>
        [Test]
        public void MaxDrivingTimeTest()
        {
            // TODO unit test for the property 'MaxDrivingTime'
        }
        /// <summary>
        /// Test the property 'InitialDrivingTime'
        /// </summary>
        [Test]
        public void InitialDrivingTimeTest()
        {
            // TODO unit test for the property 'InitialDrivingTime'
        }
        /// <summary>
        /// Test the property 'PossibleSplit'
        /// </summary>
        [Test]
        public void PossibleSplitTest()
        {
            // TODO unit test for the property 'PossibleSplit'
        }

    }

}
