#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* GraphHopper Directions API
* You use the GraphHopper Directions API to add route planning, navigation and route optimization to your software. E.g. the Routing API has turn instructions and elevation data and the Route Optimization API solves your logistic problems and supports various constraints like time window and capacity restrictions. Also it is possible to get all distances between all locations with our fast Matrix API.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIAlgorithm.h"
#import "OAIConfiguration.h"
#import "OAICostMatrix.h"
#import "OAIObjective.h"
#import "OAIRelation.h"
#import "OAIService.h"
#import "OAIShipment.h"
#import "OAIVehicle.h"
#import "OAIVehicleType.h"
@protocol OAIAlgorithm;
@class OAIAlgorithm;
@protocol OAIConfiguration;
@class OAIConfiguration;
@protocol OAICostMatrix;
@class OAICostMatrix;
@protocol OAIObjective;
@class OAIObjective;
@protocol OAIRelation;
@class OAIRelation;
@protocol OAIService;
@class OAIService;
@protocol OAIShipment;
@class OAIShipment;
@protocol OAIVehicle;
@class OAIVehicle;
@protocol OAIVehicleType;
@class OAIVehicleType;



@protocol OAIRequest
@end

@interface OAIRequest : OAIObject

/* An array of vehicles that can be employed [optional]
 */
@property(nonatomic) NSArray<OAIVehicle>* vehicles;
/* An array of vehicle types [optional]
 */
@property(nonatomic) NSArray<OAIVehicleType>* vehicleTypes;
/* An array of services [optional]
 */
@property(nonatomic) NSArray<OAIService>* services;
/* An array of shipments [optional]
 */
@property(nonatomic) NSArray<OAIShipment>* shipments;
/* An array of relations [optional]
 */
@property(nonatomic) NSArray<OAIRelation>* relations;

@property(nonatomic) OAIAlgorithm* algorithm;
/* An array of objectives [optional]
 */
@property(nonatomic) NSArray<OAIObjective>* objectives;
/* An array of cost matrices [optional]
 */
@property(nonatomic) NSArray<OAICostMatrix>* costMatrices;

@property(nonatomic) OAIConfiguration* configuration;

@end
